Update Dockerfile.ubuntu-static

diff --git a/Dockerfile.ubuntu-static b/Dockerfile.ubuntu-static
--- a/Dockerfile.ubuntu-static
+++ b/Dockerfile.ubuntu-static
@@ -352,7 +352,10 @@ RUN mkdir qt-build && cd qt-build && \
       -DQT_FEATURE_system_png=ON \
       -DQT_FEATURE_system_jpeg=ON \
       -DQT_FEATURE_system_freetype=ON \
-      -DQT_FEATURE_system_harfbuzz=ON && \
+      -DQT_FEATURE_system_harfbuzz=ON || true && \
+    echo "----- config.summary -----" && cat config.summary || true && \
+    echo "----- CMakeError.log -----" && cat CMakeFiles/CMakeError.log || true && \
+    echo "----- CMakeOutput.log -----" && cat CMakeFiles/CMakeOutput.log || true && \
     cmake --build . --parallel && \
     cmake --install .
 
