Update Dockerfile.ubuntu-static

diff --git a/Dockerfile.ubuntu-static b/Dockerfile.ubuntu-static
--- a/Dockerfile.ubuntu-static
+++ b/Dockerfile.ubuntu-static
@@ -414,22 +414,7 @@ RUN wget https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15
     env \
       PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig" \
       CPPFLAGS="-I/usr/local/include" \
-      LDFLAGS="-L/usr/local/lib -static" \
-      CFLAGS="-fPIC" \
-    ./configure --prefix=/usr/local --enable-static --disable-shared --with-pic \
-        --enable-libxml2 && \
-    make -j$(nproc) && \
-    make install&& \
-    echo "===> Checking libfontconfig.a symbols (libxml2 / freetype / FT_Get_BDF_Property)" && \
-    nm /usr/local/lib/libfontconfig.a | grep -E 'xml|FT_Get_BDF_Property|freetype' || (echo "ERROR: missing expected symbols!" && exit 1)
-
-# fontconfig (static)
-RUN wget https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.gz && \
-    tar -xf fontconfig-2.15.0.tar.gz && cd fontconfig-2.15.0 && \
-    env \
-      PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig" \
-      CPPFLAGS="-I/usr/local/include" \
-      LDFLAGS="-L/usr/local/lib -lxml2 -lfreetype -lz -static" \
+      LDFLAGS="-L/usr/local/lib -lxml2 -lfreetype -lz -lxcb-util-image -lxcb-util -static" \
       CFLAGS="-fPIC" \
     ./configure --prefix=/usr/local --enable-static --disable-shared --with-pic \
         --enable-libxml2 && \
@@ -437,7 +422,9 @@ RUN wget https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15
     make install && \
     echo "===> Checking libfontconfig.a symbols (xmlParseChunk / FT_Get_BDF_Property)" && \
     nm /usr/local/lib/libfontconfig.a | grep -E 'xmlParseChunk|FT_Get_BDF_Property' || \
-      (echo "ERROR: missing expected symbols!" && exit 1)
+      (echo "ERROR: missing expected symbols!" && exit 1)&& \
+    echo "===> Checking libfontconfig.a symbols (libxml2 / freetype / FT_Get_BDF_Property)" && \
+    nm /usr/local/lib/libfontconfig.a | grep -E 'xml|FT_Get_BDF_Property|freetype' || (echo "ERROR: missing expected symbols!" && exit 1)
 
 # Qt取得 & ビルド
 # Download and extract Qt module source
