Update Dockerfile.ubuntu-static

diff --git a/Dockerfile.ubuntu-static b/Dockerfile.ubuntu-static
--- a/Dockerfile.ubuntu-static
+++ b/Dockerfile.ubuntu-static
@@ -393,15 +393,21 @@ WORKDIR /build
 RUN echo "Dumping openssl.pc:" && \
     cat /usr/local/lib64/pkgconfig/openssl.pc && \
     echo "Checking for Libs.private:" && \
-    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/openssl.pc || echo "Libs.private not found"
+    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/openssl.pc || echo "Libs.private not found" && \
+    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib64/pkgconfig" \
+    pkg-config --static --exists openssl || (echo "Missing static pkg-config: openssl")
 RUN echo "Dumping libssl.pc:" && \
     cat /usr/local/lib64/pkgconfig/libssl.pc && \
     echo "Checking for Libs.private:" && \
-    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/libssl.pc || echo "Libs.private not found"
+    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/libssl.pc || echo "Libs.private not found" && \
+    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib64/pkgconfig" \
+    pkg-config --static --exists ssl || (echo "Missing static pkg-config: $ssl")
 RUN echo "Dumping libcrypto.pc:" && \
     cat /usr/local/lib64/pkgconfig/libcrypto.pc && \
     echo "Checking for Libs.private:" && \
-    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/libcrypto.pc || echo "Libs.private not found"
+    grep -i '^Libs.private:' /usr/local/lib64/pkgconfig/libcrypto.pc || echo "Libs.private not found" && \
+    PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib64/pkgconfig" \
+    pkg-config --static --exists crypto || (echo "Missing static pkg-config: crypto")
 
 # 必須ライブラリ一覧
 RUN set -ex && \
