Update Dockerfile.ubuntu-static

diff --git a/Dockerfile.ubuntu-static b/Dockerfile.ubuntu-static
--- a/Dockerfile.ubuntu-static
+++ b/Dockerfile.ubuntu-static
@@ -361,10 +361,7 @@ RUN wget https://xorg.freedesktop.org/archive/individual/lib/xcb-util-image-${XC
     tar -xzf xcb-util-image-${XCB_UTIL_IMAGE_VERSION}.tar.gz && \
     cd xcb-util-image-${XCB_UTIL_IMAGE_VERSION} && \
     ./configure --prefix=/usr/local --with-xcb=/usr --disable-shared --enable-static --with-pic && \
-    make -j$(nproc) && make install && \
-    echo "===> Checking libxcb-image.a symbols (xcb_create_pixmap_from_bitmap_data / xcb_aux_create_gc)" && \
-    nm /usr/local/lib/libxcb-image.a | grep -E 'xcb_create_pixmap_from_bitmap_data|xcb_aux_create_gc' || \
-      (echo "ERROR: missing expected symbols!" && exit 1)&& \
+    make -j$(nproc) && make install 
 
 # xcb-util-keysyms
 RUN wget https://xorg.freedesktop.org/archive/individual/lib/xcb-util-keysyms-${XCB_UTIL_KEYSYMS_VERSION}.tar.gz && \
@@ -427,7 +424,7 @@ RUN wget https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15
     nm /usr/local/lib/libfontconfig.a | grep -E 'xmlParseChunk|FT_Get_BDF_Property' || \
       (echo "ERROR: missing expected symbols!" && exit 1)&& \
     echo "===> Checking libfontconfig.a symbols (libxml2 / freetype / FT_Get_BDF_Property)" && \
-    nm /usr/local/lib/libfontconfig.a | grep -E 'xml|FT_Get_BDF_Property|freetype' || (echo "ERROR: missing expected symbols!" && exit 1)
+    nm /usr/local/lib/libfontconfig.a | grep -E 'xml|FcConfig|freetype' || (echo "ERROR: missing expected symbols!" && exit 1)
 
 # Qt取得 & ビルド
 # Download and extract Qt module source
