Dockerfile.ubuntu-static を更新

diff --git a/Dockerfile.ubuntu-static b/Dockerfile.ubuntu-static
--- a/Dockerfile.ubuntu-static
+++ b/Dockerfile.ubuntu-static
@@ -293,19 +293,11 @@ RUN wget https://xorg.freedesktop.org/archive/individual/xcb/xcb-util-cursor-${X
     ./configure --prefix=/usr/local --disable-shared --enable-static && \
     make -j$(nproc) && make install
 
-# xcb-util-wm の .pc ファイル手動修正（必要なら）
-RUN echo 'prefix=/usr/local
-exec_prefix=${prefix}
-libdir=${exec_prefix}/lib
-includedir=${prefix}/include
-
-Name: xcb-icccm
-Description: XCB ICCCM utilities
-Version: 0.4.1
-Requires: xcb
-Libs: -L${libdir} -lxcb-icccm
-Libs.private: -lxcb-icccm
-Cflags: -I${includedir}' > /usr/local/lib/pkgconfig/
+# 省略: 各種 xcb-util 系ライブラリのビルド後に入れる確認用ステップ
+RUN echo "---- Installed .pc files ----" && \
+    ls -1 /usr/local/lib/pkgconfig/*.pc && \
+    echo "---- xcb-icccm.pc content ----" && \
+    cat /usr/local/lib/pkgconfig/xcb-icccm.pc || echo "xcb-icccm.pc not found"
 
 
 RUN find /usr/local/lib -name "*.a" -exec echo "Checking {}" \; -exec nm {} \; | grep xcb_icccm_size_hints_set_win_gravity || echo "OK: xcb_icccm_size_hints_set_win_gravity not found"
